Add workarounds for `NoSuchMethodError` from DRM framework exceptions
Issue: androidx/media#1145

PiperOrigin-RevId: 613573868
(cherry picked from commit f3864160a20277cededc08b4148985112b7a6bb6)